osx_image: xcode11
language: swift
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project QGridTestApp/QGridTestApp.xcodeproj -scheme QGridTestApp -sdk iphonesimulator -destination 'OS=13.0,name=iPhone XÊ€,platform=iOS Simulator' -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
